### ISSUE TITLE
Update terminology from thesis text

### ISSUE THREAD

**Issue by mkovatsc** [t2trg/t2trg-rest-iot#10]
@ektrah

**Comment by mkovatsc** [comment]
@ektrah What is the status here (of your thesis)?
Erik provided some updates.
How do we proceed with the "application state" issue?

**Comment by mkovatsc** [comment]
Mike Amundsen suggested:
> I suggest using the words "client state" and "resource state" in section 3.2 of draft-keranen-t2trg-rest-iot. This more clearly identifies who is responsible for which state elements and avoids discussions about "application" and "session" definitions.

**Comment by akeranen** [comment]
Klaus has nothing to add
