### ISSUE TITLE
Rule of thumb for good hypermedia-driven design

### ISSUE THREAD

**Issue by mkovatsc** [t2trg/t2trg-rest-iot#17]
I just gave this advice and it might be a good rule of thumb:

Assuming human-readable representation formats (i.e., text-based not binary) and a client supporting the URI scheme used, a good rule of thumb for a good hypermedia-driven design is the following:
A developer should only need an entry point URI to drive the application. All further information how to navigate through the application (links) and how to construct more complex requests (forms) are published by the server(s). There must be no need for additional, out-of-band information (e.g., API specification).

For machines, a well-chosen set of information needs to be shared a priori to agree on machine-understandable semantics. (Agreeing on the exact semantics of terms for relation types and data elements will of course also help the developer.)

**Comment by cabo** [comment]
Yes, except that text-based doesn't mean human-readable (as exemplified by JSON -- in reality you need a formatting tool to look at any instances that aren't entirely trivial).  More important is that the format is self-describing (and the tool you need to look at that not too obscure).

**Comment by mkovatsc** [comment]
Yes, yes, all this is already in the assumptions to get a concise rule of thumb :)

Next iteration:

Assuming self-describing representation formats (i.e., text-based with carefully chosen terms or processible by a formatting tool) and a client supporting the URI scheme used, a good rule of thumb for a good hypermedia-driven design is the following:
A developer should only need an entry point URI to drive the application. All further information how to navigate through the application (links) and how to construct more complex requests (forms) are published by the server(s). There must be no need for additional, out-of-band information (e.g., API specification).

For machines, a well-chosen set of information needs to be shared a priori to agree on machine-understandable semantics. (Agreeing on the exact semantics of terms for relation types and data elements will of course also help the developer.)
