### ISSUE TITLE
Include summary of hartke-core-apps

### ISSUE THREAD

**Issue by mkovatsc** [t2trg/t2trg-rest-iot#2]
Communication among different parties needs to agree upon some shared concepts => media types, rel types.

Argument for loose coupling, open system, etc.

**Comment by mkovatsc** [comment]
Take over section 3 (Template with list of what needs to be shared a priori).
Check other bits, e.g., URI design.

**Comment by mkovatsc** [comment]
Check why "System design" is under "Basics".

**Comment by akeranen** [comment]
Addressed in https://tools.ietf.org/html/draft-irtf-t2trg-rest-iot-04#section-5.4
