### ISSUE TITLE
Hierarchical and non-hierarchical URI parts

### ISSUE THREAD

**Issue by akeranen** [t2trg/t2trg-rest-iot#4]
> On 22 Mar 2016, at 14:08, Simpson, Robby (GE Energy Connections) <robby.simpson@ge.com> wrote:
> In reading draft-keranen-t2trg-rest-iot-01 I note the following:
> The path is hierarchical; the query is non-hierarchical.
> It is my understanding that this statement is subject to debate.

http://www.ietf.org/mail-archive/web/t2trg/current/msg00186.html

**Comment by mkovatsc** [comment]
Fixed in PR #5
