### ISSUE TITLE
Major: Explain the role of Actions in IoT (opposed to central state transfer pattern)

### ISSUE THREAD

**Issue by mkovatsc** [t2trg/t2trg-rest-iot#62]
From 3.2. System Design

> This is usually done by retrieving the current state, modifying the state on the client side, and transferring the new state to the server in the form of new representations -- rather than calling a service and modifying the state on the server side.

Carsten's comment: "This plays down actions a lot"

Might be best suited for the "Calling a procedure" section.

**Comment by akeranen** [comment]
The "calling a procedure" section explains the other option in quite some detail so I think adding a cross-ref there is good enough fix here. Now in PR #81.
