### ISSUE TITLE
Editorial: Uniform Interface appearing in 3.5, but discussed in 4.4

### ISSUE THREAD

**Issue by mkovatsc** [t2trg/t2trg-rest-iot#63]
> As part of the Uniform Interface constraint, each method can have certain properties that give guarantees to clients.

**Comment by akeranen** [comment]
Actually first time in [3.2](https://www.ietf.org/archive/id/draft-irtf-t2trg-rest-iot-12.html#section-3.2) with reference to 4.4 
> Overall, this allows to realize a Uniform Interface (see Section 4.4), which enables loose coupling between clients and servers.

**Comment by akeranen** [comment]
Seems like simplest way to fix this is to add another cross-ref. Now in PR 80.
