### ISSUE TITLE
Minor: Include RFC 8132 *ETCH

### ISSUE THREAD

**Issue by mkovatsc** [t2trg/t2trg-rest-iot#67]
Issue was raised in 6.2.3.  Conversion, but also affects methods section.

**Comment by mkovatsc** [comment]
Methods section has *ETCH and correct reference, however, the following related comment on the HTTP counterpart:

> Minor: Mention https://datatracker.ietf.org/doc/draft-ietf-httpbis-safe-method-w-body/ ?

**Comment by akeranen** [comment]
At the moment the draft is expired. If it's revived and going towards RFC, could add a ref.

**Comment by cabo** [comment]
We could mention that the HTTPBIS WG is chewing on it, but there is no active draft at the moment.
