### ISSUE TITLE
Minor: SotA for syntactic/structural validation

### ISSUE THREAD

**Issue by mkovatsc** [t2trg/t2trg-rest-iot#71]
Section 4.4. refers to JSON Schema at the end as an example for syntactic/structural validation and has the comment:

> I think we have a better reference for structural (syntactic) validation.

Still unclear which would be that better reference that is used in practice. Could be picked up in WISHI call.

**Comment by akeranen** [comment]
CDDL could be mentioned for structural/syntactic validation and perhaps mention also CBOR as a generic format relevant in this context.
